var gemMesh =
{
  "version" : "0.1.0",

  "comment" : "Generated by MeshLab JSON Exporter",

  "id"      : 1,
  "name"    : "mesh",

  "vertices" :
  [
    {
      "name"       : "position_buffer",
      "size"       : 3,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        30, 0, 0, 0, 50, 0, 0, 0, 30, -30, 0, 0, 0, -50, 0, 0, 0, -30
      ]
    },

    {
      "name"       : "normal_buffer",
      "size"       : 3,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        1067.07, 0, 0, 0, 1778.45, 0, 0, 0, 1067.07, -1067.07, 0, 0, 0, -1778.45, 0, 0, 0, -1067.07
      ]
    }
  ],

  "connectivity" :
  [
    {
      "name"      : "triangles",
      "mode"      : "triangles_list",
      "indexed"   : true,
      "indexType" : "uint32",
      "indices"   :
      [
        0, 1, 2, 0, 2, 4, 0, 4, 5, 0, 5, 1, 3, 1, 5, 3, 5, 4, 3, 4, 2, 3, 2, 1
      ]
    }
  ],

  "mapping" :
  [
    {
      "name"       : "standard",
      "primitives" : "triangles",
      "attributes" :
      [
        {
          "source"   : "position_buffer",
          "semantic" : "position",
          "set"      : 0
        },
        {
          "source"   : "normal_buffer",
          "semantic" : "normal",
          "set"      : 0
        }
      ]
    }
  ],

  "custom" : null
}
