var mummyMesh =
{
  "version" : "0.1.0",

  "comment" : "Generated by MeshLab JSON Exporter",

  "id"      : 1,
  "name"    : "mesh",

  "vertices" :
  [
    {
      "name"       : "position_buffer",
      "size"       : 3,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        4.37114e-07, 5, 0, -4.37114e-07, -5, 0, -5, 5, 0, -2.5, 5, 4.33013, 2.5, 5, 4.33013, 5, 5, 6.12323e-16, 2.5, 5, -4.33013, -2.5, 5, -4.33013
      ]
    },

    {
      "name"       : "normal_buffer",
      "size"       : 3,
      "type"       : "float32",
      "normalized" : false,
      "values"     :
      [
        8.74228e-08, 1, 0, -8.74228e-08, -1, 0, -1, 8.74228e-08, 0, -0.5, 4.37114e-08, 0.866025, 0.5, -4.37114e-08, 0.866025, 1, -8.74228e-08, 0, 0.5, -4.37114e-08, -0.866025, -0.5, 4.37114e-08, -0.866025
      ]
    }
  ],

  "connectivity" :
  [
    {
      "name"      : "triangles",
      "mode"      : "triangles_list",
      "indexed"   : true,
      "indexType" : "uint32",
      "indices"   :
      [
        0, 2, 3, 0, 3, 4, 0, 4, 5, 0, 5, 6, 0, 6, 7, 0, 7, 2, 1, 3, 2, 1, 4, 3, 1, 5, 4, 1, 6, 5,
        1, 7, 6, 1, 2, 7
      ]
    }
  ],

  "mapping" :
  [
    {
      "name"       : "standard",
      "primitives" : "triangles",
      "attributes" :
      [
        {
          "source"   : "position_buffer",
          "semantic" : "position",
          "set"      : 0
        },
        {
          "source"   : "normal_buffer",
          "semantic" : "normal",
          "set"      : 0
        }
      ]
    }
  ],

  "custom" : null
}
